config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  resources :users

  get "admin" => "sessions#new"
  resources :apologies
  resource :session
  resources :pages

  root 'pages#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  
end #routes

app/models/apology.rb
# frozen_string_literal: true

class Apology < ApplicationRecord
  CHARACTER_MAX = 170

  before_validation :assign_image, on: :create

  validates :body, presence: true, length: { maximum: CHARACTER_MAX }
  validates :image, presence: true

  scope :ordered, -> { all.order('created_at DESC') }

  def character_max
    CHARACTER_MAX
  end

  def assign_image
    self.image = Image.sample
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guaranteed_user.rb
# frozen_string_literal: true

class GuaranteedUser
  class << self
    def find_by(parms)
      User.find_by(parms) || NullUser.new
    end
  end
end

app/models/image.rb
# frozen_string_literal: true

class Image
  IMAGES_DIRECTORY = '/assets/images/'
  ACCEPTABLE_FORMATS = %w[jpg jpeg png].freeze

  class << self
    delegate :sample, to: :image_file_names

    # I prefer this version over the rubocop suggestion to delegate
    # because its intention is more clear to me.

    # def sample
    #   image_file_names.sample
    # end

    private

    def image_file_names
      filepaths.map { |path| File.basename(path) }
    end

    def filepaths
      Dir.glob("*#{IMAGES_DIRECTORY}*.{#{ACCEPTABLE_FORMATS.join(',')}}")
    end
  end
end

app/models/null_user.rb
# frozen_string_literal: true

class NullUser
  def authenticate(_)
    false
  end

  def username
    'guest'
  end
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  before_validation :generate_slug

  validates :name, presence: true
  validates :body, presence: true, length: { maximum: 210 }

  validates :slug, uniqueness: { case_sensitive: false }

  PUBLISH_STATUS = %w[Published Unpublished].freeze
  validates :publish_status, inclusion: { in: PUBLISH_STATUS }

  scope :published, -> { where(publish_status: 'Published').order('name') }

  def generate_slug
    self.slug = name.downcase
    self.slug ||= name.parameterize if name
  end

  def to_param
    slug
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :password, length: { minimum: 5, allow_blank: true }
  validates :first_name, :last_name, presence: true
  validates :email,
            presence: true,
            format: /\A\S+@\S+\z/,
            length: { minimum: 5 },
            uniqueness: { case_sensitive: false }
  validates :username,
            presence: true,
            format: /\A[A-Z0-9]+\z/i,
            uniqueness: { case_sensitive: false }

  before_save :format_username
  before_save :format_email

  def format_username
    self.username = username.downcase
  end

  def format_email
    self.email = email.downcase
  end

  def to_param
    username
  end
end

app/controllers/apologies_controller.rb
# frozen_string_literal: true

class ApologiesController < ApplicationController
  before_action :set_apology, only: %i[show edit update destroy]
  before_action :require_signin, except: %i[show new create]

  def index
    @apologies = Apology.ordered
  end

  def show; end

  def new
    @apology = Apology.new
  end

  def edit; end

  def create
    @apology = Apology.new(apology_params)

    if @apology.save
      redirect_to @apology, flash: { social_media_share: 'Send via Social Media' }
    else
      flash.now[:alert] = 'Something went wrong. Ryan apologizes for that.'
      render :new
    end
  end

  def update
    if @apology.update(apology_params)
      redirect_to @apology, notice: message(@apology, 'updated')
    else
      render :edit
    end
  end

  def destroy
    @apology.destroy
    redirect_to apologies_url, notice: message(@apology, 'deleted')
  end

  private

  def message(apology, action)
    "#{apology.class.name} was successfully #{action}."
  end

  def set_apology
    @apology = Apology.find(params[:id])
  end

  def apology_params
    params.require(:apology).permit(:body, :image)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  before_action :set_pages

  private

  def require_signin
    return nil if current_user
    session[:intended_url] = request.url
    redirect_to new_session_url, alert: 'Please sign in first'
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def current_user?(user)
    current_user == user
  end
  helper_method :current_user?

  # This makes the pages show up in the navbar
  def set_pages
    @pages = Page.all
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :set_page, only: %i[show edit update destroy]
  before_action :require_signin, except: %i[show home]

  def home
    @page = Page.find_by!(slug: 'static-home-page')
  end

  def index
    @pages = Page.all
  end

  def show; end

  def new
    @page = Page.new
  end

  def edit; end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to @page, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  def update
    if @page.update(page_params)
      redirect_to @page, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to pages_url, notice: 'Page was successfully destroyed.'
  end

  private

  def set_page
    @page = Page.find_by!(slug: params[:id])
  end

  def page_params
    params.require(:page).permit(:name, :slug, :heading, :body, :publish_status)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = GuaranteedUser.find_by(email: params[:email])

    if user.authenticate(params[:password])
      create_user_session(user)
    else
      display_error(user)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You're now signed out!"
  end

  private

  def create_user_session(user)
    session[:user_id] = user.id
    flash[:notice] = "Welcome back, #{user.first_name}!"
    redirect_to(session[:intended_url] || user)
    session[:intended_url] = nil
  end

  def display_error
    flash.now[:alert] = 'Invalid email/password combination!'
    render :new
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_signin

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    @user.save
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: message(@user, 'updated')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    # TODO: make this so a user can delete another user without being signed out
    session[:user_id] = nil
    redirect_to root_url, alert: message(@user, 'deleted')
  end

  private

  def message(user, action)
    "#{user.first_name}'s account has been successfully #{action}."
  end

  def set_user
    @user = User.find_by!(username: params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :username,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def page_title
    if content_for?(:title)
      "Sorry Girl - #{content_for(:title)}"
    else
      'Sorry Girl - The Apology You Needed to Hear, but from Ryan Gosling'
    end
  end

  def page_description
    if content_for?(:description)
      "Sorry Girl - #{content_for(:description)}"
    else
      page_title
    end
  end
end

app/views/apologies/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 offset-sm-2 col-lg-4 offset-lg-4">
    <%= form_for(apology) do |f| %>
      <%= render partial: 'shared/errors', locals: {object: apology} %>

      <div id="apology-form" class="field">
        <div class="character-count-container"><span id="character-count"><%= apology.character_max %></span> characters remaining</div>
        <%= f.text_area :body, autofocus: true, required: true, placeholder: "Hey Girl, I'm sorry I was such a jerkface...", class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit class: 'btn btn-md btn-primary btn-block' %>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'apologies' %>

app/views/apologies/edit.html.erb
<% content_for(:title, "Edit Apology") %>

<div class="form-box">

  <%= render 'form', apology: @apology %>

  <%= link_to 'Show', @apology %> |
  <%= link_to 'Back', apologies_path %>

</div> <!-- form-box -->

app/views/apologies/index.html.erb
<% content_for(:title, "All Apologies") %>

<div class="container">

<h1>Apologies Index</h1>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Note</th>
      <th colspan="3">Manage</th>
    </tr>
  </thead>

  <tbody>
    <% @apologies.each do |apology| %>
      <tr>
       <td><%= link_to image_tag(apology.image, :class => "index-image"), apology %></td>
        <td><%= truncate(apology.body, length: 75, separator: ' ') %></td>
        <td><%= link_to 'Show', apology %></td>
        <td><%= link_to 'Edit', edit_apology_path(apology) %></td>
        <td><%= link_to 'Delete', apology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to ' Write an Apology', new_apology_path, class: "btn btn-sm btn-primary" %>

</div> <!-- container -->

app/views/apologies/new.html.erb
<% content_for(:title, "Write an Apology") %>

<%= render 'form', apology: @apology %>

app/views/apologies/show.html.erb
<% content_for(:description, @apology.body) %>

<div class="apology-wrapper">
  <div class="create-button-wrapper">
    <%= link_to "Edit", edit_apology_path, class: "btn btn-info btn-sm" if current_user%>
  </div>

  <div class='apology-container'>
    <div>
      <%= image_tag(@apology.image) %>
    </div>
      
    <div class="right-column">
      <p class='note'><%= @apology.body %></p>
      <p class='note'>Love,<br>Ryan</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= raw page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Halant:300,400|Rock+Salt" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/header" %>
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Page Name" %><br>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <% unless @page.new_record? %>
    <div class="field">
      <%= f.label :slug, "Permalink" %><br>
      <%= f.text_field :slug %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, cols: 40, rows: 7 %>
  </div>
  <div class="field">
    <%= f.label :publish_status, "Set Publish Status" %><br>
    <%= f.select :publish_status, Page::PUBLISH_STATUS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<% content_for(:title, "Editing: #{@page.name}") %>

<div class="form-box">

  <h1>Editing: <%= @page.name %></h1>

  <%= render 'form' %>

  <%= link_to 'Show', @page %> |
  <%= link_to 'Back', pages_path %>  
</div> <!-- form-box -->

app/views/pages/home.html.erb
<div class="apology-wrapper">
  <div class="create-button-wrapper">
    <% if current_user %>
    <%= link_to " Edit", edit_page_path(@page), class: "btn btn-primary btn-sm" %>
    <% end %><!-- current_user -->
  </div> <!-- create-button-wrapper -->
</div> <!-- apology-wrapper -->


<div class='apology-container'>
  <div>
    <%= image_tag("ryan-gosling01.jpg") %>
  </div>
    
  <div class="right-column">
    <p class='note'>Hey Girl,</p>
    <p class='note'><%= @page.body %></p>

    <div class="btn-wrapper">
      <%= link_to "Write an Apology", new_apology_path, class: "btn btn-primary btn-xl" %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<% content_for(:title, "Pages Index") %>

<div class="container">

  <h1>Pages Index</h1>
  <%= link_to ' New Page', new_page_path, class: "btn btn-default btn-sm fa fa-plus" %>


  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Publish Status</th>
        <th>Permalink</th>
        <th>Heading</th>
        <th>Body</th>
        <th colspan="3">Manage</th>
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.name %></td>
          <td><%= page.publish_status %></td>
          <td><%= page.slug %></td>
          <td><%= page.heading %></td>
          <td><%= page.body %></td>
          <td><%= link_to 'Show', page %></td>
          <td><%= link_to 'Edit', edit_page_path(page) %></td>
          <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

</div><!-- container -->

app/views/pages/new.html.erb
<% content_for(:title, "New Page") %>

<div class="form-box">

  <h1>Create a New Page</h1>

  <%= render 'form' %>

  <%= link_to 'Back', pages_path %>
  
</div> <!-- form-box -->

app/views/pages/show.html.erb
<% content_for(:title, @page.name) %>
<% content_for(:description, @page.body) %>

<div class="apology-wrapper">

  <div class="create-button-wrapper">
    <% if current_user %>
    <%= link_to " Edit", edit_page_path, class: "btn btn-default btn-sm fa fa-pencil" %>
    <% end %>
  </div> <!-- create-button-wrapper -->
</div> <!-- apology-wrapper -->


<div class='apology-container'>
  <div>
    <%= image_tag("ryan-gosling01.jpg") %>
  </div>
    
  <div class="right-column">
    <h3><%= @page.heading %></h3>
    <p class='note'><%= @page.body %></p>
  </div>
</div>

app/views/shareable/partials/_button_wrapper.html.erb
<%= yield %>

app/views/shareable/partials/_parent_wrapper.html.erb
<nav class="share">
  <%= yield %>
</nav>

app/views/shared/_admin_nav_items.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Manage Content
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to "Apologies Index", apologies_path, class: 'dropdown-item' %>
    <%= link_to "Create New Apology", new_apology_path, class: 'dropdown-item' %>
    <%= link_to "Pages Index", pages_path, class: 'dropdown-item' %>
  </div>
</li>

<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_user.first_name %>
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to 'Sign Out', session_path, method: :delete, class: 'dropdown-item' %>
    <%= link_to 'My Profile', current_user, class: 'dropdown-item' %>
    <%= link_to 'All Users', users_path, class: 'dropdown-item' %>
  </div>
</li>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this apology from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_alert.html.erb
<p id="alert"><%= message %></p>

app/views/shared/_flash_notice.html.erb
<p id="notice"><%= message %></p>

app/views/shared/_flash_social_media_share.html.erb
<div class="show-share-partial">
  <h3>Now <%= message %>:</h3>
  <%= rails_social_share_button_tag(page_description, :url => request.original_url, desc: page_description, title: page_title) %>
</div>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <%= render partial: "shared/flash_#{type}", locals: { message: message } %>
<% end %>

app/views/shared/_footer.html.erb
<div class='social-share-button'>
  <%= rails_social_share_button_tag(page_description, :url => request.original_url, desc: page_description, title: page_title) %>
</div>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-bottom">
  <a class="navbar-brand" href="/"><span class="brand">Sorry Girl</span></a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="/pages/about" class="nav-link">About</a>
      </li>
      <li class="nav-item">
        <%= link_to "Write an Apology", new_apology_path, class: 'nav-link' %>
      </li>
      <%= render partial: 'shared/admin_nav_items' if current_user %>
    </ul>
    <ul class="pull-right copyright">
      <li><%= link_to "Admin", admin_path %></li>
      <li>Copyright &copy; <%= Time.now.year %></li>
    </ul>
  </div>
</nav>

app/views/shared/_header.html.erb
<header>
  <h1 class="title"><%= link_to "Ryan Gosling Apologizes", new_apology_path %></h1>
  <h2 class="subtitle">(for you)</h2>
</header>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <% if @user.new_record? %>
      <%= f.submit "Create Account" %>
    <% else %>
      <%= f.submit "Update Account" %>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for(:title, "Editing: #{@user.first_name} #{@user.last_name}") %>

<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% content_for(:title, "Users Index") %>



<div class="container">
   
  
<h1>Users Index</h1>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Username</th>
      <th colspan="3">Manage</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure you want to delete " + user.first_name + "'s account? This action cannot be undone." } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to ' New User', new_user_path, class: "btn btn-default btn-sm fa fa-plus" %>

</div> <!-- container -->

app/views/users/new.html.erb
<% content_for(:title, "New User") %>

<div class="form-box">

<h1>New User</h1>

<%= render 'form' %>

</div> <!-- form-box -->

app/views/users/show.html.erb
<% content_for(:title, "#{@user.first_name} #{@user.last_name}") %>



<div class="form-box">
  
  <p>
    <strong>Name:</strong>
    <%= @user.first_name %> <%= @user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= @user.username %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-default btn-sm" %> 
  <%= link_to 'Cancel', users_path, class: "btn btn-default btn-sm"  %>

</div> <!-- form-box -->